### ISSUE TITLE
wrong behaviour with fake email

### ISSUE THREAD

**Issue by LucaCellamare** [zhijing-jin/email2country#1]
When parsing for example a fake email like this : 
addr="example@fake.whatever"
email=Email(addr)
print(email.country)--->the output is :  'Italy'
Why?

**Comment by zhijing-jin** [comment]
Hi LucaCellamare,

Thanks for proposing some corner cases to improve the package! I tried your case and **the library actually outputs correctly:**

```
>>> from email2country import Email
>>> addr="example@fake.whatever"
>>> email=Email(addr)
>>> email.country
[Info] Country not found for "fake.whatever"
```

One suggestion is to try `pip install --upgrade git+git://github.com/zhijing-jin/email2country.git` again and see if your current version is up-to-date.

Should you have any inquiries, feel free to follow up :).

Cheers,
Zhijing

**Comment by zhijing-jin** [comment]
As everything looks correct, I will close this for the moment. Feel free to re-open it if you have any questions :).
